services:
  db:
    platform: linux/amd64
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: ${HOST_PG_PORT:-5432}
        protocol: tcp
        mode: host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

  libretranslate:
    platform: linux/amd64
    image: libretranslate/libretranslate:latest
    ports:
      - "5001:5000"
    environment:
      LT_LOAD_ONLY: en,pt,pb
      LT_UPDATE_MODELS: "false"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 90
      start_period: 60s

  jsonserver:
    platform: linux/amd64
    build:
      context: ./docker/json-server
    volumes:
      - ./docker/json-server/db.json:/data/db.json
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:6000"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 5s

  redis:
    platform: linux/amd64
    image: redis:7
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redis_data:/data
    ports:
      - target: 6379
        published: ${HOST_REDIS_PORT:-6379}
        protocol: tcp
        mode: host

  web:
    platform: linux/amd64
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    image: comment-analysis-system:web
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    env_file:
      - .env
    volumes:
      - .:/app:cached
      - bundle:/gems
      - ./.local/history:/history
    depends_on:
      db: { condition: service_healthy }
      redis: { condition: service_started }
      jsonserver: { condition: service_started }
      libretranslate: { condition: service_started }
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  sidekiq:
    platform: linux/amd64
    tty: true
    stdin_open: true
    image: comment-analysis-system:web
    command: bundle exec sidekiq -C config/sidekiq.yml
    env_file:
      - .env
    volumes:
      - .:/app:cached
      - bundle:/gems
      - ./.local/history:/history
    depends_on:
      web: { condition: service_healthy }
      db: { condition: service_healthy }
      redis: { condition: service_started }

  nginx:
    platform: linux/amd64
    image: nginx:1.27-alpine
    depends_on:
      - web
      - jsonserver
      - libretranslate
    ports:
      - "${HOST_HTTP_PORT:-80}:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  seed_json:
    profiles: ["tools"]
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: comment-analysis-system:web-amd64
    entrypoint: ["bundle","exec","ruby"]
    command: ["tools/generate_api_data.rb"]
    env_file:
      - .env
    environment:
      JSON_OUT: /json/db.json
    volumes:
      - .:/app
      - bundle:/gems
      - ./docker/json-server:/json

volumes:
  bundle:
  pg_data:
  redis_data:
